---
- name: Set up node exporter container
  docker_container:
    name: node-exporter
    image: prom/node-exporter:v1.2.2
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - "9100:9100"
    networks:
      - monitor
    env:
      DATABASE_URL: "mysql+pymysql://microblog:{{ mysql_password }}@{{ groups['database'][0] }}:3306/microblog"
    restart_policy: unless-stopped
    command: "{{ item }}"
    with_items:
      - '--path.procfs=/host/proc'
        - '--path.rootfs=/rootfs'
        - '--path.sysfs=/host/sys'
        - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'




