---
- name: Start the database docker container
  docker_container:
    name: mysql
    image: mysql/mysql-server:5.7
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      MYSQL_DATABASE: "microblog"
      MYSQL_USER: "microblog"
      MYSQL_PASSWORD: "{{ mysql_password }}"
    ports:
      - "3306:3306"
    restart_policy: always
