---
- name: Get latest image from docker hub
  ansible.builtin.shell: docker pull ampheris/microblog:node-exporter

- name: Start the microblog docker container
  ansible.builtin.docker_container:
    name: microblog
    image: ampheris/microblog:node-exporter
    ports:
        - "8000:5000"
    env:
      DATABASE_URL: "mysql+pymysql://microblog:{{ mysql_password }}@{{ groups['database'][0] }}:3306/microblog"
    restart_policy: always
